### ISSUE TITLE
ONNX model names

### ISSUE THREAD

**Issue by canaxx** [FaceONNX/FaceONNX#10]
Can you please give information about the feature extraction model [recognition_resnet27.onnx] ? Is this model based on paper https://arxiv.org/pdf/1703.08388.pdf ?

**Comment by asiryan** [comment]
No, it is based on SeqFace: https://github.com/huangyangyu/SeqFace

**Comment by canaxx** [comment]
Thax for the reply. I have checked the Seqface project link. Below is a note from their readme file;

```

**Model-and-Result

We released our ResNet-27 model, which can be downloaded by the link below. The model was trained in caffe, please refer to our paper for the detailed training process.

Caffe: ResNet-27 @BaiduDrive, @GoogleDrive (non-commercial use only)

Performance:
Dataset 	Model 	Dataset 	LFW 	YTF
SeqFace 	1 ResNet-27 	MS-Celeb-1M + Celeb-Seq 	99.80 	98.00
SeqFace 	1 ResNet-64 	MS-Celeb-1M + Celeb-Seq 	99.83 	98.12**
```
Regarding above statement it seems the model is Resnet-27. Also your ONNX file name is : "recognition_resnet27.onnx" . Can we re-clear out that ?

**Comment by asiryan** [comment]
> Thax for the reply. I have checked the Seqface project link. Below is a note from their readme file;
> 
> ```
> 
> **Model-and-Result
> 
> We released our **_ResNet-27_** model, which can be downloaded by the link below. The model was trained in caffe, please refer to our paper for the detailed training process.
> 
> Caffe: ResNet-27 @BaiduDrive, @GoogleDrive (non-commercial use only)
> 
> Performance:
> Dataset 	Model 	Dataset 	LFW 	YTF
> SeqFace 	1 ResNet-27 	MS-Celeb-1M + Celeb-Seq 	99.80 	98.00
> SeqFace 	1 ResNet-64 	MS-Celeb-1M + Celeb-Seq 	99.83 	98.12**
> ```
> 
> Regarding above statement it seems the model is Resnet-27. Also your ONNX file name is : "recognition_resnet27.onnx" . Can we re-clear out that ?

Yes, it's the same model. So?)
