### ISSUE TITLE
Does not work in UWP (SoftwareBitmap)

### ISSUE THREAD

**Issue by venetasoft** [FaceONNX/FaceONNX#11]
It would be great if we could have it to work with SoftwareBitmap (or WriteableBitmap) in order to be able to use it on UWP apps too. This version compiles on UWP, but fires an "unsupported in this platform" error at runtime...

Thank you

**Comment by asiryan** [comment]
Thank you for feedback! I think in general Bitmap (or BitmapImage, WirteableBitmap) is not the best story in terms of image processing. I plan to use this library in the future: https://github.com/dlemstra/Magick.NET. Can you check if it will work in uwp?

**Comment by venetasoft** [comment]
Thanks to you for your awesome work!!!

Yes I used Magik.NET in some UWP Apps I developed for Lumia phones (RIP), it's very "old", so I suppose it is still even more solid and fast :)

I was trying to add your awesome FaceONNX library into this project for a home project: `https://github.com/dao-duc-tung/face-detection-uwp-onnx/tree/main/src/FaceDetector](https://github.com/dao-duc-tung/face-detection-uwp-onnx/tree/main/src/FaceDetector` 
but unfortunately System.Drawing.Bitmap works with GDI+ only, not available in UWP.

In UWP Microsoft introduced the Windows.Graphics.Imaging.SoftwareBitmap object, and this is how to get the pixels from it: [https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/imaging#create-or-edit-a-softwarebitmap-programmatically](url).

The sample project get a Emgu.CV.Mat from a SoftwareBitmap (coming from the webcam or from a file) with this code:

`public unsafe static Mat ConvertSoftwareBitmapToMat(SoftwareBitmap bmp, int nChannel = 4)
        {          
            Mat mat = null;
            try
            {
                if (bmp.BitmapPixelFormat != BitmapPixelFormat.Bgra8 ||
                    bmp.BitmapAlphaMode != BitmapAlphaMode.Ignore)
                {
                    bmp = SoftwareBitmap.Convert(bmp, BitmapPixelFormat.Bgra8, BitmapAlphaMode.Ignore);
                }

                using (BitmapBuffer buffer = bmp.LockBuffer(BitmapBufferAccessMode.Read))
                {
                    using (var reference = buffer.CreateReference())
                    {
                        byte* data;
                        uint capacity;
                        ((IMemoryBufferByteAccess)reference).GetBuffer(out data, out capacity);
                        mat = new Mat(new System.Drawing.Size(bmp.PixelWidth, bmp.PixelHeight), DepthType.Cv8U, nChannel, (IntPtr)data, (int)capacity / bmp.PixelHeight);
                    }
                }
            }
            catch (ObjectDisposedException e)
            {
                Debug.WriteLine(e.Message);
            }
            return mat;
        }`
        
        FaceONNX could be easily ported to UWP with the above code, the only parts I am not able to port from your code are the matrix operations you do on 'tensors[][]' array in the "Forward" methods:
        
        Basically the code I am not able to port to Mat is:
        
        //Emotion:
        tensors.Compute(256, Matrice.Div);
	var inputData = tensors.Average();
        
        //age:
        tensors.Compute(new float[] { 104, 117, 123 }, Matrice.Sub);
	var inputData = tensors.Merge(true);
        
       //gender:
       tensors.Compute(new float[] { 104, 117, 123 }, Matrice.Sub);
       var inputData = tensors.Merge(true);
       
       //FaceBeauty:
       tensors.Compute(new float[] { 104, 117, 123 }, Matrice.Sub);
       tensors.Compute(255, Matrice.Div);
       var inputData = tensors.Merge(true); 
      
      How can I apply those matrix operations to a 'Emgu.CV.Mat' (or, alternatively, to a Tensor<float>, or to a List<NamedOnnxValue>).. ?
      
      
      Thank you very much for your help (and I hope this will be a hint for you to publish an UWP version of your stellar lib!)

**Comment by asiryan** [comment]
Hello! I added an extension for Forward methods with float[][,] argument (image in BGR terms). Now you can convert your image to float[][,] format and use FaceONNX wherever you want. Check this out https://www.nuget.org/packages/FaceONNX/2.1.0.1

**Comment by venetasoft** [comment]
Valery Asiryan thank you very much ! Now your lib can be fully used in Xamarin Forms too !!!

**Comment by asiryan** [comment]
Awesome! Thank you!

**Comment by venetasoft** [comment]
Could yuou please suggest a fast way to convert a byte[] array (the pixels array of the SoftwareBitmap) to the float[][] needed by the new overload ? Thank you again.

**Comment by asiryan** [comment]
Use this conversion example for BitmapData from [UMapx.NET](https://github.com/UMapx/UMapx/blob/master/sources/Imaging/BitmapMatrix.cs)

```
        /// <summary>
        /// Converts a Bitmap to an RGB structure with or without alpha-channel.
        /// </summary>
        /// <param name="bmData">Bitmap data</param>
        /// <param name="alpha">Alpha-channel</param>
        /// <returns>RGBA structure array</returns>
        public unsafe static float[][,] ToRGB(BitmapData bmData, bool alpha = false)
        {
            // params
            int width = bmData.Width, height = bmData.Height, stride = bmData.Stride;
            byte* p = (byte*)bmData.Scan0.ToPointer();

            // matrices
            float[,] x = new float[height, width];
            float[,] y = new float[height, width];
            float[,] z = new float[height, width];

            // with alpha channel
            if (alpha)
            {
                float[,] a = new float[height, width];

                Parallel.For(0, height, j =>
                {
                    int i, k, jstride = j * stride;

                    for (i = 0; i < width; i++)
                    {
                        // shift:
                        k = jstride + i * 4;

                        // color
                        x[j, i] = p[k + 0] / 255.0f;
                        y[j, i] = p[k + 1] / 255.0f;
                        z[j, i] = p[k + 2] / 255.0f;
                        a[j, i] = p[k + 3] / 255.0f;
                    }
                });

                return new float[][,] { x, y, z, a };
            }

            // without alpha channel
            Parallel.For(0, height, j =>
            {
                int i, k, jstride = j * stride;

                for (i = 0; i < width; i++)
                {
                    // shift:
                    k = jstride + i * 4;

                    // color
                    x[j, i] = p[k + 0] / 255.0f;
                    y[j, i] = p[k + 1] / 255.0f;
                    z[j, i] = p[k + 2] / 255.0f;
                }
            });

            return new float[][,] { x, y, z };
        }
```

**Comment by venetasoft** [comment]
Thank you very much!
