### ISSUE TITLE
Anti Face Spoofing on 2d Face Object (bitmap)

### ISSUE THREAD

**Issue by abunoman2003** [FaceONNX/FaceONNX#12]
Thanks for the great works, is there any plan or anti face spoofing on 2d Face or if exist, any guide would be appreciated.

**Comment by asiryan** [comment]
Hello! Thank you for feedback. Yes, FaceONNX contains a face anti-spoofing model: https://github.com/FaceONNX/FaceONNX/blob/main/netstandard/FaceONNX/face/classes/FaceDepthClassifier.cs

But you need a 3D camera to get face depth. Check out these face verification examples:
https://github.com/FaceONNX/FaceONNX/tree/main/netstandard/Examples/AntispoofingDepthClassification
https://github.com/FaceONNX/FaceONNX/tree/main/netstandard/Experiments/RealSenseFaceID

**Comment by abunoman2003** [comment]
@asiryan Thank you so much for your promt reply. I checked it's working good, but how about 2d image/face?

**Comment by asiryan** [comment]
@abunoman2003 the fact is that I looked and tested similar solutions based on neural networks in 2020 and the results were very deplorable. Such protection methods are very sensitive to lighting, as well as image quality. I was able to solve this problem only using a 3D representation of the face in the form of depth. I admit that perhaps technological progress has made it possible to make more accurate neural networks, in this case it is necessary to conduct research and see what is available from the available options in open source.

**Comment by asiryan** [comment]
I have tested these models
https://github.com/SoftwareGift/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019
https://github.com/ZhangYuanhan-AI/CelebA-Spoof
https://github.com/zeusees/HyperFAS
https://github.com/OeslleLucena/FASNet
https://github.com/juan-csv/face_liveness_detection-Anti-spoofing
https://github.com/kprokofi/light-weight-face-anti-spoofing
https://github.com/emadeldeen24/face-anti-spoofing

**Comment by abunoman2003** [comment]
Hi @asiryan 
Hope you are doing great. How is going things? Is it possible add functionality as per the following link?
https://github.com/Stevencibambo/face-antispoofing-model
Thanks
