### ISSUE TITLE
Anti spoofing How to create simmilar images 

### ISSUE THREAD

**Issue by mla3beh** [FaceONNX/FaceONNX#13]
The sample is working fine with the sample images, but can you please tell me how to generate new images with the same features as the sample ??

**Comment by asiryan** [comment]
@mla3beh hello! Use my experiment: https://github.com/FaceONNX/FaceONNX/tree/main/netstandard/Experiments/RealSenseFaceID

**Comment by mla3beh** [comment]
thank you
