### ISSUE TITLE
How well does faceONNX resist face spoofing?

### ISSUE THREAD

**Issue by ADD-eNavarro** [FaceONNX/FaceONNX#2]
Hello.
First things first, thanks for your work, looks awesome.
I was wondering if you have considered security in your implementation, or are planning to include some, to prevent face spoofing.

**Comment by asiryan** [comment]
Hey! Thanks for the feedback.
As for anti-spoofing, this technology requires special sensors and cameras. At the same time, there are several fundamentally different approaches to solving the problem of identity and security verification. For these reasons, the corresponding neural network will not be available within the FaceONNX library.

**Comment by ADD-eNavarro** [comment]
Thanks for such a fast response.
Well, actually that's exactly what I'm after, a PAD system that requires no particular hardware. I've been looking into [MiDaS ](https://github.com/intel-isl/MiDaS) for monocular depth perception, in the belief that pairing face detection with depth could achieve this result, for example through face landmark points depth comparison, since a presentation attack would be flat (unless it's a mask).
Anyway, even without antispoofing, I consider your work is great. Thank you again for it.

**Comment by asiryan** [comment]
Hi! I want to present new feature of FaceONNX -> FaceDepthClassifier. It can be used for 3D antispoofing algorithm. Check this out.

**Comment by ADD-eNavarro** [comment]
That is AWESOME!
I'll have a look and try the examples, thank you so much!

**Comment by ADD-eNavarro** [comment]
Well, that would be nice for sure. But then you link your system to some particular hardware, which I wouldn't but of course it's up to you.
I'll be lloking into the face depth example this weekend. Can't wait!

**Comment by asiryan** [comment]
@ADD-eNavarro Work on the new components of the library has been completed. The current version, 2.0.0.1, includes all the necessary anti-spoofing tools. Also follow my new [repository](https://github.com/asiryan/RealSenseFaceID), I will post the FaceID in it.
