### ISSUE TITLE
Do you have benchmark about the model?

### ISSUE THREAD

**Issue by stereomatchingkiss** [FaceONNX/FaceONNX#20]
Like LFW, megaface, mscelab? Thanks

**Comment by asiryan** [comment]
@stereomatchingkiss hello! What model you are talking about?

**Comment by stereomatchingkiss** [comment]
> @stereomatchingkiss hello! What model you are talking about?

Mainly recognition_resnet27.onnx, more precisely, benchmark of the face recognition pipeline of this project. Thanks

**Comment by asiryan** [comment]
> > @stereomatchingkiss hello! What model you are talking about?
> 
> Mainly recognition_resnet27.onnx, more precisely, benchmark of the face recognition pipeline of this project. Thanks

You can find it here
https://github.com/huangyangyu/SeqFace

**Comment by asiryan** [comment]
In my local tests this is a more accurate and strong model

**Comment by stereomatchingkiss** [comment]
> In my local tests this is a more accurate and strong model

Nice to hear that and thanks for the benchmark, I think this project will become more attractive if with benchmark. Any plan to release light weight model?

**Comment by asiryan** [comment]
> > In my local tests this is a more accurate and strong model
> 
> Nice to hear that and thanks for the benchmark, I think this project will become more attractive if with benchmark. Any plan to release light weight model?

I think no. But I want to release project for Person Recognition and Re-identification

**Comment by stereomatchingkiss** [comment]
> > > In my local tests this is a more accurate and strong model
> > 
> > 
> > Nice to hear that and thanks for the benchmark, I think this project will become more attractive if with benchmark. Any plan to release light weight model?
> 
> I think no. But I want to release project for Person Recognition and Re-identification

Nice to hear that, I am writing an open source face recognition webapp by Qt6 and [face-recognition-ncnn](https://github.com/wllkk/face-recognition-ncnn).

The results of insight face looks great and it has small model which suit for webapp(this webapp run on local machine, not suit for big model), but the pretrained model of insight face cannot use for commercial purpose.

**Comment by asiryan** [comment]
> > > > In my local tests this is a more accurate and strong model
> > > 
> > > 
> > > Nice to hear that and thanks for the benchmark, I think this project will become more attractive if with benchmark. Any plan to release light weight model?
> > 
> > 
> > I think no. But I want to release project for Person Recognition and Re-identification
> 
> Nice to hear that, I am writing an open source face recognition webapp by Qt6 and [face-recognition-ncnn](https://github.com/wllkk/face-recognition-ncnn).
> 
> The results of insight face looks great and it has small model which suit for webapp(this webapp run on local machine, not suit for big model), but the pretrained model of insight face cannot use for commercial purpose. I am finding alternative solution

Wow, send me a link to these models, I'll check it out.

**Comment by stereomatchingkiss** [comment]
> > > > > In my local tests this is a more accurate and strong model
> > > > 
> > > > 
> > > > Nice to hear that and thanks for the benchmark, I think this project will become more attractive if with benchmark. Any plan to release light weight model?
> > > 
> > > 
> > > I think no. But I want to release project for Person Recognition and Re-identification
> > 
> > 
> > Nice to hear that, I am writing an open source face recognition webapp by Qt6 and [face-recognition-ncnn](https://github.com/wllkk/face-recognition-ncnn).
> > The results of insight face looks great and it has small model which suit for webapp(this webapp run on local machine, not suit for big model), but the pretrained model of insight face cannot use for commercial purpose. I am finding alternative solution
> 
> Wow, send me a link to these models, I'll check it out.

[Here](https://github.com/wllkk/face-recognition-ncnn).

**Comment by asiryan** [comment]
> > > > > > In my local tests this is a more accurate and strong model
> > > > > 
> > > > > 
> > > > > Nice to hear that and thanks for the benchmark, I think this project will become more attractive if with benchmark. Any plan to release light weight model?
> > > > 
> > > > 
> > > > I think no. But I want to release project for Person Recognition and Re-identification
> > > 
> > > 
> > > Nice to hear that, I am writing an open source face recognition webapp by Qt6 and [face-recognition-ncnn](https://github.com/wllkk/face-recognition-ncnn).
> > > The results of insight face looks great and it has small model which suit for webapp(this webapp run on local machine, not suit for big model), but the pretrained model of insight face cannot use for commercial purpose. I am finding alternative solution
> > 
> > 
> > Wow, send me a link to these models, I'll check it out.
> 
> [Here](https://github.com/wllkk/face-recognition-ncnn). [More benchmark and models link](https://github.com/deepinsight/insightface/tree/master/model_zoo), but they do not release the mobileNet model

Thank you!
