### ISSUE TITLE
GPU Support - how does it work?

### ISSUE THREAD

**Issue by Webreaper** [FaceONNX/FaceONNX#23]
I'd really like to be able to build in GPU support and have it use that if a GPU is available, but still work and fall back to CPU if no GPU is present on the system. 

Is this possible?

**Comment by asiryan** [comment]
Hello! Yes, sure. You can use FaceONNX.Gpu and FaceONNX.Addons.Gpu packages. check this example https://github.com/FaceONNX/FaceONNX/blob/main/netstandard/Examples/GPUPerfomanceTests/Program.cs
