### ISSUE TITLE
CPU vs GPU packages.

### ISSUE THREAD

**Issue by vpenades** [FaceONNX/FaceONNX#25]
Hi, I've have some questions and suggestions regarding FaceOnnx package dependencies.

As I understand it, FaceOnnx uses CPU, and FaceOnnx.GPU uses Gpu (nVidia-Cuda?)

Onnx exposes more providers than just that, in fact, we use Onnx.DirectML as default.

Now, I am not asking to publish FaceOnnx for every provider, but the opposite.

My suggestion to you is that, instead of depending on "Microsoft.ML.OnnxRuntime"  yo make the package depend on "Microsoft.ML.OnnxRuntime.Managed"

.Managed is just the abstract API surface and cannot run by itself because it's missing the provider, but the advantage is that you can make a package with some ONNX logic inside, and then the consumer of the package can append any provider.

The practical result would be that you only need to publish a single FaceOnnx package depending on Microsoft.ML.OnnxRuntime.Managed , and then the projects using it can choose & switch between providers.

**Comment by asiryan** [comment]
Hello, @vpenades !
Thank you for your report. I think this is a good idea and I should to check it out.

**Comment by asiryan** [comment]
@vpenades where can I find information about the Microsoft.ML.OnnxRuntime.Managed package to confirm what you said?

**Comment by vpenades** [comment]
I actually use that architecture in my own packages. what I do is this:

PackageWithSomeONNXLogic => references Microsoft.ML.OnnxRuntime.Managed

ApplicationProject => references PackageWithSomeONNXLogic & Microsoft.ML.OnnxRuntime. [DirectML | GPU | SomeOtherProvider ]

Basically, the .Managed package exposes the API and entry points, and the rest of the packages provide the native libraries required to run.

That's why the different onnxruntime libraries are mutually exclusive, but that's not the case with Managed, which can be mixed with the others.

And that does the trick.

I don't know if there's information about this, I just wanted to resolve the provider switching issue for my own packages, and figured it out after inspecting the OnnxRuntime packages dependency tree, which led me to find that the ".managed" package is the common denominator for all.

**Comment by asiryan** [comment]
@vpenades very good point, thank you so much! I will add it to the FaceONNX projects and thus mark the GPU versions as obsolete.

**Comment by georg-jung** [comment]
Can confirm that this approach works for me too in [FaceAiSharp](https://github.com/georg-jung/FaceAiSharp). Happy to answer questions if you have any.

This approach is also used by e.g. [Microsoft.ML.OnnxTransformer](https://www.nuget.org/packages/Microsoft.ML.OnnxTransformer/4.0.0-preview.24162.2)

**Comment by vpenades** [comment]
Btw, in the commit I see references to OnnxRuntime 1.9.0 ....  checking nuget.org, I can see the highest version is 1.17.3 ?

**Comment by asiryan** [comment]
> Btw, in the commit I see references to OnnxRuntime 1.9.0 .... checking nuget.org, I can see the highest version is 1.17.3 ? isn't 1.9.0 a bit outdated?

Yes, I can update it to the latest version

**Comment by asiryan** [comment]
> Can confirm that this approach works for me too in [FaceAiSharp](https://github.com/georg-jung/FaceAiSharp). Happy to answer questions if you have any.
> 
> This approach is also used by e.g. [Microsoft.ML.OnnxTransformer](https://www.nuget.org/packages/Microsoft.ML.OnnxTransformer/4.0.0-preview.24162.2)

Great, thank you!

**Comment by asiryan** [comment]
https://github.com/FaceONNX/FaceONNX/releases/tag/v4.0.1.1
