### ISSUE TITLE
GPU Utilisation

### ISSUE THREAD

**Issue by etempm** [FaceONNX/FaceONNX#26]
Hello, first of all, thank you for your great work and sharing. I'm testing on the sample on the GPU. My graphics card is an RTX 3090 and the example uses the processor at 100% when running on the CPU. However, when running on the GPU, there is a maximum usage of 40%. What would you recommend I do to fully utilize the GPU resource?

**Comment by asiryan** [comment]
Hello! Thank you very much! It depends only on ONNXRuntime, I think you need to research it.
