### ISSUE TITLE
Exception thrown when running FaceONNX on Xamarin forms android app

### ISSUE THREAD

**Issue by sukanzubair** [FaceONNX/FaceONNX#28]
When trying to utilize FaceOnnx on a xamarin forms app, an exception is thrown

 System.DllNotFoundException: 'onnxruntime assembly:<unknown assembly> type:<unknown type> member:(null)'

![image](https://github.com/user-attachments/assets/3fb7f6d8-78cc-42e2-9e40-90028767da6c)

![image](https://github.com/user-attachments/assets/5d317e71-b8ff-482e-8ff1-57f31d56f26b)

**Comment by sukanzubair** [comment]
I have tried version 1.0.3.1 and the latest version 4.0.2.1

**Comment by asiryan** [comment]
@sukanzubair hello! I didn't work with Xamarin.Forst. But I think that you have to add onnxruntime package to your project
https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime
