### ISSUE TITLE
Does it support Linux-x64  and Linux-arm64 ?

### ISSUE THREAD

**Issue by yangjieshao** [FaceONNX/FaceONNX#29]
Does it support Linux-x64  and Linux-arm64 ?

**Comment by asiryan** [comment]
Hello! Yes, it should. But you need to use other libraries to process images instead of System.Drawing. Please check this example which provides an example of cross-platform features of FaceONNX:
https://github.com/FaceONNX/FaceONNX/blob/main/netstandard/Examples/FaceEmbeddingsClassification/Program.cs

**Comment by yangjieshao** [comment]
我看见项目依赖了 `UMapx`
I see that the project dependent on `UMapx`

`UMapx` 依赖了 `System.Drawing.Common`
`UMapx` dependent on ` System.Drawing.Common`

但是 据我所知从 net7 开始` System.Drawing.Common` 已经不能在linux使用
But as i known starting from net7, `System Drawing. Common`  can no longer be used on Linux
[System.Drawing.Common config switch removed](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/system-drawing)

所以真的可以在 linux 运行么
So can it really run on Linux ?

**Comment by yangjieshao** [comment]
Thanks

我尝试通过删除 `UMapx` 中的 `System.Drawing.Common` 依赖来验证 `FaceONNX` 是否在 linux 里并未使用到 `System.Drawing.Common`
I tried to verify that `FaceONNX` does not use `System.Drawing.Common` in linux by removing the `System.Drawing.Common` dependency in `UMapx`

好消息是 在linux中 `FaceONNX` 确实并未因为 `UMapx` 使用到 `System.Drawing.Common`
The good news is that in Linux, `FaceONNX` does not use `System.Drawing.Common` because `UMapx`

**Comment by yangjieshao** [comment]
![image](https://github.com/user-attachments/assets/6a567912-7102-41a8-b246-39b420b294bc)
看上去 不支持 linux-arm64
It seems that linux-arm64 is not supported

**Comment by yangjieshao** [comment]
Microsoft.ML.OnnxRuntime.1.9.0   do not had linux-arm64
Microsoft.ML.OnnxRuntime.1.20.0 had linux-arm64
![image](https://github.com/user-attachments/assets/a1833ff4-ea88-4f09-9fcf-32c4d4e8686f)

**Comment by asiryan** [comment]
@yangjieshao oh, apparently, I have to update ONNXRuntime which is used in FaceONNX and derivatives libraries, right?
Could provide a link where that support of Linux is described?

**Comment by yangjieshao** [comment]
我是根据下载后的nuget目录看看的
I looked at it based on the downloaded Nuget directory

在 `.nuget\packages\microsoft.ml.onnxruntime\1.9.0\runtimes`  目录下并没有 `linux-arm64`
There is no `linux-arm64` in the `.nuget\packages\microsoft.ml.onnxruntime\1.9.0\runtimes` directory

在 `.nuget\packages\microsoft.ml.onnxruntime\1.20.1\runtimes` 目录下才找到 `linux-arm64`
`linux-arm64` was found in the `.nuget\packages\microsoft.ml.onnxruntime\1.20.1\runtimes` directory

我只缓存了 `1.9.0` 和 `1.20.1` 所以并不清楚从哪个版本开始有  `linux-arm64`
I only cached `1.9.0` and `1.20.1` so I don't know from which version `linux-arm64` is available

**Comment by yangjieshao** [comment]
使用 1.20.1 在 linus-arm64 已测试成功
Tested successfully on linus-arm64 using 1.20.1

只是需要手动将 `libonnxruntime.so` 和 `libonnxruntime_providers_shared.so` 从 .nuget 目录复制到发布目录
Just need to manually copy `libonnxruntime.so` and `libonnxruntime_providers_shared.so` from the .nuget directory to the release directory

**Comment by asiryan** [comment]
@yangjieshao I suppose you can install every ONNXRuntime version you want. Because FaceONNX does not include it and requires [Microsoft.ML.OnnxRuntime.Managed](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.Managed/) only.

**Comment by yangjieshao** [comment]
我想 至少在example里 应该更新成最新的 [Microsoft.ML.OnnxRuntime.Managed](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.Managed/)
I think at least in the example, it should be updated to the latest [Microsoft.ML.OnnxRuntime.Managed](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.Managed/)

**Comment by asiryan** [comment]
Okay, I will check it
