### ISSUE TITLE
也许，应该在本项目提醒使用 `microsoft.ml.onnxruntime` 默认会被收集遥测数据 (Perhaps, it should be reminded in this project that using `microsoft.ml.onnxruntime` will collect telemetry data by default)

### ISSUE THREAD

**Issue by yangjieshao** [FaceONNX/FaceONNX#32]
![image](https://github.com/user-attachments/assets/2b162bb2-f7f4-468b-868b-e7526b8eee18)
也许，应该在本项目提醒使用 `microsoft.ml.onnxruntime` 默认会被收集遥测数据 
(Perhaps, it should be reminded in this project that using `microsoft.ml.onnxruntime` will collect telemetry data by default)

毕竟使用本项目的时候并不会意识到使用了 `microsoft.ml.onnxruntime` 会开启遥测
After all, when using this project, you will not realize that using `microsoft.ml.onnxruntime` will enable telemetry

对于一些数据敏感的项目这是不可接受的
This is unacceptable for some data-sensitive projects

并在本项目提供关闭遥测的方式
And this project provides a way to turn off telemetry

这样对于使用本项目的人来说  `microsoft.ml.onnxruntime` 应该是无感的
In this way, people who use this project should not feel the need for `microsoft.ml.onnxruntime`

**Comment by asiryan** [comment]
Hi there! @yangjieshao it's not a FaceONNX issue, I am sorry.

**Comment by yangjieshao** [comment]
是的 ，这不是FaceONNX代码上的问题
Yes, this is not a problem with the FaceONNX code

但是对于用户来说，他并不知道FaceONNX使用了microsoft.ml.onnxruntime
But for the user, he does not know that FaceONNX uses microsoft.ml.onnxruntime

他就无法提前知道microsoft.ml.onnxruntime带来的额外条款
He would not know in advance the additional terms brought by microsoft.ml.onnxruntime

我认为 FaceONNX 应该在readme上做到提醒的义务
I think FaceONNX should fulfill its obligation to remind in the readme
