### ISSUE TITLE
人脸照片上下颠倒时`Face68Landmarks.RotationAngle`  返回的角度错误 (`Face68Landmarks.RotationAngle` returns the wrong angle when the face photo is upside down)

### ISSUE THREAD

**Issue by yangjieshao** [FaceONNX/FaceONNX#33]
人脸照片上下颠倒时`Face68Landmarks.RotationAngle`  返回的角度错误
`Face68Landmarks.RotationAngle` returns the wrong angle when the face photo is upside down

![1](https://github.com/user-attachments/assets/733c9f8c-ebf7-461b-a8de-a5b09c88db17)
![1](https://github.com/user-attachments/assets/30094863-8f21-4ad1-a6df-30215d37a73e)

**Comment by asiryan** [comment]
@yangjieshao agreed. In case of face rotation, I recommend you use 5 landmarks from FaceDetector

https://github.com/FaceONNX/FaceONNX/blob/777566e762ac807f5cc6b197e49563f07ceab983/netstandard/FaceONNX/face/models/FaceDetectionResult.cs#L40

**Comment by yangjieshao** [comment]
Face5Landmarks 并没有解决人脸上下颠倒的问题
Face5Landmarks does not solve the problem of upside-down faces


<details>
<summary>
Code 
</summary>

![image](https://github.com/user-attachments/assets/393c87eb-b166-4ecd-9221-1e7cdbc76fa1)

```

            foreach (var file in files)
            {
                using var bitmap = new Bitmap(file);
                var outputs = faceDetector.Forward(bitmap);

                foreach (var output in outputs)
                {
                    var paintData = new PaintData()
                    {
                        Rectangle = output.Box,
                        Title = $"{output.Points.RotationAngle:0.00}",
                        Points= output.Points.All
                    };
                    using var graphics = Graphics.FromImage(bitmap);
                    
                    painter.Draw(graphics, paintData);
                }

                var filename = Path.GetFileName(file);
                bitmap.Save(Path.Combine(path, filename));
                Console.WriteLine($"Image: [{filename}] --> detected [{outputs.Length}] faces");
            }
```

</details>

<details>
<summary>
original pic
</summary>

![1-0](https://github.com/user-attachments/assets/635ee3a1-194d-48db-b6f7-497cc76a80ba)
![1-1](https://github.com/user-attachments/assets/c570ef11-3fb1-4a10-b9dd-408fa4c5cd2b)
![1-2](https://github.com/user-attachments/assets/3fa8e2b3-d64f-4039-8d10-ef217fbf4c59)

</details>

<details>

<summary>
results pic
</summary>

![1-0](https://github.com/user-attachments/assets/25f6b6d9-dad5-42dc-8f4b-558db1def074)
![1-1](https://github.com/user-attachments/assets/b6a54990-ba29-4728-a58d-17808a62b692)
![1-2](https://github.com/user-attachments/assets/33db374b-ad56-4a8d-ba23-31905d6dce98)

</details>

**Comment by yangjieshao** [comment]
[images.zip](https://github.com/user-attachments/files/18056145/images.zip)
![image](https://github.com/user-attachments/assets/0820af9a-73df-4d01-8164-0512e3138d68)

```

                foreach (var output in outputs)
                {
                    var mouthPoint = Points.GetMeanPoint(output.Points.Mouth);
                    var title = string.Empty;
                    if (mouthPoint.Y > output.Points.RightEye.Y
                        && mouthPoint.Y > output.Points.LeftEye.Y)
                    {
                        title = "↑";
                    }
                    else if (mouthPoint.Y < output.Points.RightEye.Y
                        && mouthPoint.Y < output.Points.LeftEye.Y)
                    {
                        title = "↓";
                    }

                    var paintData = new PaintData()
                    {
                        Rectangle = output.Box,
                        Title = $"{output.Points.RotationAngle:0.00} {title}",
                        Points= output.Points.All
                    };
                    using var graphics = Graphics.FromImage(bitmap);
                    
                    painter.Draw(graphics, paintData);
                }
```
![1-4](https://github.com/user-attachments/assets/f216ca64-d49a-4228-83f1-1331582b937a)
![Snipaste_2024-12-08_20-14-34](https://github.com/user-attachments/assets/6b195003-e273-44a7-b8a3-9c6742633640)

**Comment by asiryan** [comment]
@yangjieshao hello! Oh, I see. Looks bad and, honestly, I have no idea how to help you. This is a very strange case.
