### ISSUE TITLE
Can facial comparison be achieved? Similarity

### ISSUE THREAD

**Issue by bbhxwl** [FaceONNX/FaceONNX#34]
Can facial comparison be achieved? Similarity

**Comment by asiryan** [comment]
Certainly! Please try this example out
https://github.com/FaceONNX/FaceONNX/tree/main/netstandard/Examples/FaceEmbeddingsClassification

**Comment by bbhxwl** [comment]
> Certainly! Please try this example out https://github.com/FaceONNX/FaceONNX/tree/main/netstandard/Examples/FaceEmbeddingsClassification

How many people can he compare with? Can 10000 people do it?

**Comment by asiryan** [comment]
> > Certainly! Please try this example out https://github.com/FaceONNX/FaceONNX/tree/main/netstandard/Examples/FaceEmbeddingsClassification
> 
> How many people can he compare with? Can 10000 people do it?

I think yes. I've tested FaceONNX on 20k unique images of people and it works well. But honestly, it depends on quality of images.
